package com.aetheria.input;

public enum Action {
    MOVE_UP, MOVE_DOWN, MOVE_LEFT, MOVE_RIGHT,
    RUN, INTERACT, ATTACK,
    OPEN_INVENTORY, PAUSE,
    CONFIRM, CANCEL,
    DEBUG_TOGGLE,
    COMBAT_ACTION_1, COMBAT_ACTION_2, COMBAT_ACTION_3, COMBAT_ACTION_4
}
